export const userInfo = {
  id: 1,
  nickname: "haijiao-vip",
  avatar: "1",
  description: "海角社区内容很棒，祝海角社区越办越好。",
  topicCount: 0,
  videoCount: 0,
  commentCount: 0,
  fansCount: 0,
  favoriteCount: 0,
  status: 0,
  sex: 0,
  vip: 4,
  vipExpiresTime: "2099-01-01 00:00:00",
  certified: false,
  certVideo: false,
  certProfessor: false,
  famous: false,
  forbidden: false,
  tags: null,
  role: 0,
  diamondConsume: 0,
  title: {
    id: 0,
    name: "",
    consume: 0,
    consumeEnd: 0,
    icon: "",
  },
  friendStatus: false,
  voiceStatus: false,
  videoStatus: false,
  voiceMoneyType: 0,
  voiceAmount: 0,
  videoMoneyType: 0,
  videoAmount: 0,
  depositMoney: 0,
  phone: "",
  userBank: null,
  parentId: 0,
  gold: 99999999,
  diamond: 99999999,
  passwordSet: true,
  payPasswordSet: true,
  popularity: 10,
  topicLikeNum: 0,
  bindUser: "",
  username: "forget8",
  email: "",
  emailVerified: false,
  createTime: "2024-04-23 13:45:19",
  lastLoginTime: "2024-04-25 16:52:13",
  lastLoginIp: "127.0.0.1",
  certifiedExpired: false,
  certProfessorExpired: false,
  certVideoExpired: false,
  hasGaEnabled: false,
};
